### PR TITLE
Retain dots from the module name

### PR DESCRIPTION
**Pull request by jcbhmr**
<table><td>

before<br>
image

<td>

after<br>
image

</table>

honestly im not entirely sure of the difference between .name and .getFriendlyFullName(). it appears as though .getFriendlyFullName() is a wrapper around .name with some magic? do you want the magic frm getFriendlyFullName() too or no? idk which is better 🤷‍♂️

<details><summary>code from typedoc in my node_modules for the getFriendlyFullName() func</summary>

```js
/**
     * Return the full name of this reflection, with signature names dropped if possible without
     * introducing ambiguity in the name.
     */
    getFriendlyFullName() {
        if (this.parent && !this.parent.isProject()) {
            if (this.kindOf(kind_1.ReflectionKind.ConstructorSignature |
                kind_1.ReflectionKind.CallSignature |
                kind_1.ReflectionKind.GetSignature |
                kind_1.ReflectionKind.SetSignature)) {
                return this.parent.getFriendlyFullName();
            }
            return this.parent.getFriendlyFullName() + "." + this.name;
        }
        else {
            return this.name;
        }
    }
```

</details>

use case that prompted this: investigating using TypeDoc for https://github.com/zloirock/core-js with module names like array.at or object.assign or similar. those got mangled due to the `.split(".")` stuff

https://github.com/felipecrs/typedoc-plugin-rename-defaults/blob/b34891030e6ba1e3e545672469d374299e35a717/index.js#L43

<table><td>

before<br>
image

<td>

after<br>
image

</table>

-----
<a href="https://stackblitz.com/~/github/jcbhmr/typedoc-plugin-rename-defaults/tree/jcbhmr%2Fpatch-85337">Review PR in StackBlitz Codeflow</a> _Submitted with [StackBlitz Codeflow](https://stackblitz.com/~/github/jcbhmr/typedoc-plugin-rename-defaults/tree/jcbhmr%2Fpatch-85337)._

### CODE REVIEW

**Comment by felipecrs** [comment]
Ok, in fact this brings a regression on test5 (https://github.com/felipecrs/typedoc-plugin-rename-defaults/pull/4).

Do you have any ideas on that?

### Previous

image

### After

image

**Comment by felipecrs** [comment]
Maybe we should retain the dots if a explicit jsdoc is used like test9, but otherwise discard the dots when none is set (which probably comes from the file name).

**Comment by felipecrs** [comment]
BTW, I like the usage of `getFriendlyFullName`, but we have to consider support for older versions of TypeDoc.

I don't mind bumping the minimum needed TypeDoc version though.

**Comment by jcbhmr** [comment]
given discussion in #14 and #15 i dont think this is as good of an idea as when i opened this lol. especially this:

> When using the module name we stumble upon https://github.com/felipecrs/typedoc-plugin-rename-defaults/pull/4 again. I really don't know what is the best way to handle this, but it is indeed a valid use case (when using Angular and Nest conventions).

**Pull request closed without merging**
