### PR TITLE
Convert to ESM and simplify codebase

### PR DESCRIPTION
**Pull request by jcbhmr**
- uses standard https://github.com/github/gitignore/blob/main/Node.gitignore with a typedoc-specific `docs` addition
- since this is **a single <100 line file** i don't think the benefits of strong tsc outweigh the complexity of a build step
  - means you don't have to wait 6s for `tsc` to run just to test the plugin (biggest plus side imo)
- moved test-specific typedoc stuff to the test/ folder
- used strings instead of objects for package.json stuffs
- didnt change any of the actual impl code
- didnt change readme

**you shouldnt feel obligated to accept this pr if you dont want to** this is just an idea to simplify this project in accord with its scope (a 45-line plugin lol)

-----
<a href="https://stackblitz.com/~/github/jcbhmr/typedoc-plugin-rename-defaults/tree/simplify">Review PR in StackBlitz Codeflow</a> _Submitted with [StackBlitz Codeflow](https://stackblitz.com/~/github/jcbhmr/typedoc-plugin-rename-defaults/tree/simplify)._

### CODE REVIEW

**Comment by felipecrs** [comment]
I really appreciate your PR, but please don't expect me to review this very soon as I was already comfortable with what I had.

**Comment by felipecrs** [comment]
Ok another thought. Any ideas whether converting to ESM would cause any problems for consumers? I didn't set any Node.js engine constraint, and yet this plugin is compatible with very old versions of TypeDoc.

I will do some testing.

**Comment by jcbhmr** [comment]
i wouldnt be concerned about nodejs engine support. v12+ supports esm with no `--experimental` flags and v18 is the latest LTS. i dont thing targeting nodejs v10 is a worthwhile goal. 🤷‍♂️

you can change it to cjs with a few lines. it doesn't really matter i have no strong opinions either way.

reminder:
- cjs CANNOT import esm: CANNOT do `export const hi = 4` `const { hi } = require("thing")`
- esm can import cjs: `exports.hi = 4` can be `import { hi } from "thing"`
- esm can import esm
- cjs can import cjs

to change:
```js
import { Converter } from "typedoc";

/**
 * @param {Readonly<import('typedoc').Application>} app
 */
export function load(app) {
  // ...
```
becomes
```js
"use strict"
const { Converter } = require("typedoc");

/**
 * @param {Readonly<import('typedoc').Application>} app
 */
exports.load = (app) => {
  // ...
```
(this pr has "Allow edits by maintainers" checked so feel free to make edits 😉)

**Comment by felipecrs** [comment]
Thank you. Let's go the ESM route then. :)

**Comment by felipecrs** [comment]
Later today I will wrap this up for the new release. Thank you.

**Comment by felipecrs** [comment]
Thanks a lot, I really liked this one. :)

**Comment by felipecrs** [comment]
Very helpful, I agree with your improvements and also very high quality PR.

**Pull request merged**
