### PR TITLE
Also rename `export=`

### PR DESCRIPTION
**Pull request by jcbhmr**

### CODE REVIEW

**Comment by felipecrs** [comment]
Can you please add a test case for this?

**Comment by jcbhmr** [comment]
done 👍

<table><td>

before this change<br>
image

<td>

after this change<br>
image

</table>

sidenote: the `npm run test:manual` that i used didn't actually activate the plugin lol and i spent like 10 minutes puzzling over that 🤣

test script i used:
```sh
npm run build && typedoc --plugin ./dist/index.js && npx -y serve docs
#                        ^^^^^^^^^^^^^^^^^^^^^^^^
#                        this wasn't in the either package.json scripts lol
```

**Comment by felipecrs** [comment]
> sidenote: the npm run test:manual that i used didn't actually activate the plugin lol and i spent like 10 minutes puzzling over that 🤣

Oh that has to be due https://github.com/felipecrs/typedoc-plugin-rename-defaults/pull/7. I should have updated the test command too.

**Comment by felipecrs** [comment]
Thanks a ton, very nice.

**Comment by felipecrs** [comment]
I just realized that this should have been released as a minor release, not as a patch release. 😅

**Pull request merged**
