### PR TITLE
use the @ name jsdoc tag if present

### PR DESCRIPTION
**Pull request by jcbhmr**
image
👇
image

and another:

image
👇
image

---

uses that `@name mynamehere` tag if available.

 i put this condition BEFORE the reflection.escapedName one that would use the `helloWorld` var name and return. idk if this was a good idea or not. 🤷‍♂️

-----
<a href="https://stackblitz.com/~/github/jcbhmr/typedoc-plugin-rename-defaults/tree/jcbhmr%2Fpatch-55042">Review PR in StackBlitz Codeflow</a> _Submitted with [StackBlitz Codeflow](https://stackblitz.com/~/github/jcbhmr/typedoc-plugin-rename-defaults/tree/jcbhmr%2Fpatch-55042)._

### CODE REVIEW

**Comment by jcbhmr** [comment]
oh and i should provide some background info on the @ name tag:
jsdoc tag docs: https://jsdoc.app/tags-name.html
in the real world: https://github.com/search?q=%2F%5C*+%40name%2F+language%3AJavaScript&type=code

**Comment by felipecrs** [comment]
While I can understand the usefulness of this, I am a bit hesitant whether we should do this or not, simply because this is not something TypeDoc does as well:

chrome_5WCpRiemdq

image

What do you think? Maybe we should open this discussion to the TypeDoc project itself? Or do you think this makes sense to be a feature of this plugin only?

**Comment by jcbhmr** [comment]
oh! i didnt know typedoc didnt do symbol renames!
...actually now that i think about it it kinda makes sense. you want the **name of the export in `export {theThing}`** not the `@name my-sillyName!thatTotally#isntValid%JS` to show up in docs.

yeah i dont think that my idea is that good any more 👍

there MIGHT still be some value to allowing something like this:

```js
/** @name customNameForDefaultExport */
export default "the thing"
```

but definitely dont want this happening:

```js
// extlib.js
/** @name someRandomName */
export const importantValue = 42

// mylib.js
import { importantValue } from "extlib"
export default importantValue
```
👆 AS IS in the current PR i think this would get rendered as "someRandomName"? idk.
 but still, rendering the @ name from some random decl is a bad idea in retrospect
**especially** since typedoc doesn't do it itself.

**Comment by felipecrs** [comment]
Alright, thanks for the willingness though. :)

**Pull request closed without merging**
